# Configurations
title:            The Sysadmin path
longtitle:        The Sysadmin path
author:           Marc Vilardell
description: >
  ¡Hola!
  Mi nombre es Marc Vilardell, soy un ingeniero de sistemas con más de 14 años de experiencia en el mundo de las TIC (o IT, para los amigos del inglés). A lo largo de mi carrera me he enfrentado a todo tipo de desafíos técnicos: desde configuraciones complejas hasta bugs que parecen obra de magia negra. Y si algo he aprendido, es que la documentación es tan valiosa como escasa.
  Este blog nace como mi base de conocimiento personal (KB), un lugar donde volcar lo que aprendo día a día. ¿Por qué hacerlo público? Porque creo firmemente en compartir el conocimiento. Si algo de lo que publico ayuda a alguien a resolver un problema o a ahorrar tiempo, entonces ya ha valido la pena.
  Puede que hoy, con la IA al alcance de todos, parezca que ya no hace falta escribir estas cosas. Pero quienes trabajamos en IT sabemos que las soluciones reales y específicas muchas veces no están a un prompt de distancia. Están en foros enterrados, en logs olvidados... o en blogs como este.
  Bienvenido a mi documentación técnica, mis experimentos, aprendizajes y seguramente también algún que otro tema que no tenga nada que ver con todo lo demás. Si te sirve de algo, misión cumplida.

version:          1.0
gitbook_version:  3.2.3

url:              'https://kodeenkrateia.github.io/'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
